spring.application.name=backend

# make sure to run command in terminal
# ssh -i github_actions_deploy -L 5433:localhost:5432 ubuntu@145.220.72.140
# change port to 32 if running the program locally,

spring.datasource.url=jdbc:postgresql://localhost:5433/habittracker
spring.datasource.username=habittracker_user
spring.datasource.password=NewStrongPassword123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true