spring.datasource.url=jdbc:postgresql://localhost:5432/habittracker
spring.datasource.username=habittracker_user
spring.datasource.password=NewStrongPassword123!
jwt.secret=1RhG4VpCEVsffpJM3vqSN9ixMHPBBwy/uuDDwQs8ljZA4txOpBNsWIYpeLxXuLowGv0/p/9A7kHz5LcppII7mg==
jwt.refresh-expiration-ms=2592000000